### ISSUE TITLE
Feature: do not add permissions to steps if not needed

### ISSUE THREAD

**Issue by laurentsimon** [step-security/secure-workflows#107]
See example below:
```
name: Lint
on:
  pull_request:
    branches: main
  workflow_dispatch:
    
permissions: read-all

jobs:
  lint:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
```

The 
```
permissions:
      contents: read # for actions/checkout to fetch code
```

is not necessary since the top-level permissions are `permissions: read-all`. I think you only need to add run-level permissions if they include some writes.
