### ISSUE TITLE
Mantaining the version after the full length commit SHA is generated

### ISSUE THREAD

**Issue by n-th** [step-security/secure-workflows#1087]
I would like to make a suggestion. Could we maintain the version of the commit SHA as a comment after the workflow is processed?

I mean something like this:

```yaml
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
```

```yaml
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@544eadc6bf3d226fd7a7a9f0dc5b5bf7ca0675b9 #v1.x.x
```

I think it would help us keep track of the human-readable version of the tools we are using.
