### ISSUE TITLE
Add support to update dependabot config file

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#1114]
Goal is to implement a transformation method that takes a dependabot config file and adds config for a given ecosystem to it. 

Info on this config file is here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory

Dependabot config file should be accepted in same way as GitHub Action workflow file is, either the file contents as input, or the path to the file. 
https://github.com/step-security/secure-workflows/blob/main/main.go#L93-L108

In addition, the ecosystem to be added should be passed in as a query string parameter. For first iteration, it should accept `github-actions`. We can add support for more in future updates.  

The code should check if the ecosystem already exists in the file. If yes, return it as-is. If not, add support for the ecosystem and return the updated file. 

In the `testfiles` folder, add a folder for `dependabot` and folders for `input` and `output`. The input file can be

``` yaml
version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/app"
    schedule:
      interval: "daily"
``` 

The output file should be 

``` yaml
version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/app"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
```
