### ISSUE TITLE
YAML lint issue with comments

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/secure-workflows#358]
I observed that YAML lint is complaining about the way we are adding comments:

 pull-requests: write # for reviewdog/action-golangci-lint to report issues using PR comments

https://github.com/magma/magma/pull/11442/files

**Comment by varunsh-coder** [comment]
@Devils-Knight see if you can investigate this.

**Comment by Devils-Knight** [comment]
@varunsh-coder this warning is added because `comment` rule is added in the config file, by `default` the condition for comment rule are
```yml
rules:
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2
```
if you look at ` min-spaces-from-content: 2`, minimum 2 space should be b/w comment and content whereas our `app` add only 1 space b/w comment and content.
